name: "goods_srv"
mode: "dev"
ip: "127.0.0.1"
rpcPort: 8381
httpPort: 8091
version: "v0.0.1"
start_time: "2023-08-28"
machine_id: 1

# 冒号后加空格
# 缩进是连续的两个空格
log:
  level: "debug"
  filename: "goods_srv.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "124.71.74.243"
  port: 3306
  user: "admin"
  password: "ABC12345abc"
  dbname: "tiktok_tables"
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: "124.71.74.243"
  port: 6379
  password: ""
  db: 1
  pool_size: 100

consul:
  addr: "127.0.0.1:8500"